repos:
  # Python formatting and linting
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        language_version: python3.11
        args: [--line-length=88]
        files: ^backend/

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile=black, --line-length=88]
        files: ^backend/

  # Flake8 temporarily disabled due to many existing violations
  # - repo: https://github.com/pycqa/flake8
  #   rev: 6.1.0
  #   hooks:
  #     - id: flake8
  #       args: [--max-line-length=88, --extend-ignore=E203,W503]
  #       files: ^backend/

  # Frontend linting (temporarily disabled due to config issues)
  # - repo: local
  #   hooks:
  #     - id: eslint
  #       name: ESLint (Frontend)
  #       entry: bash -c 'cd frontend && npm run lint -- --fix'
  #       language: system
  #       files: ^frontend/.*\.(js|jsx|ts|tsx)$
  #       pass_filenames: false

  # General file formatting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^.*\.(md)$
      - id: end-of-file-fixer
        exclude: ^.*\.(md)$
      - id: check-yaml
      - id: check-json
        exclude: ^(frontend/tsconfig.*\.json|frontend/node_modules/.*)$
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=1000]
