"""Initial migration

Revision ID: 74b7c8174dd8
Revises:
Create Date: 2025-08-12 17:31:29.317985

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "74b7c8174dd8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "identity_links",
        "decided_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default="now()",
        existing_nullable=False,
    )
    op.alter_column(
        "stg_roster",
        "seen_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default="now()",
        existing_nullable=False,
    )
    op.alter_column(
        "sync_events",
        "received_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default="now()",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sync_events",
        "received_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text(
            "'2025-08-12 16:57:50.482935+00'::timestamp with time zone"
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "stg_roster",
        "seen_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text(
            "'2025-08-12 16:57:50.482935+00'::timestamp with time zone"
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "identity_links",
        "decided_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text(
            "'2025-08-12 16:57:50.482935+00'::timestamp with time zone"
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
